trusts = T{
   "Shantotto",
   "Naji",
   "Kupipi",
   "Excenmille",
   "Ayame",
   "Nanaa Mihgo",
   "Curilla",
   "Volker",
   "Ajido-Marujido",
   "Trion",
   "Zeid",
   "Lion",
   "Tenzen",
   "Mihli Aliapoh",
   "Valaineral",
   "Joachim",
   "Naja Salaheem",
   "Prishe",
   "Ulmia",
   "ShikareeZ",
   "Cherukiki",
   "Iron Eater",
   "Gessho",
   "Gadalar",
   "Rainemard",
   "Ingrid",
   "Lehko Habhoka",
   "Nashmeira",
   "Zazarg",
   "Ovjang",
   "Mnejing",
   "Sakura",
   "Luzaf",
   "Najelith",
   "Aldo",
   "Moogle",
   "Fablinix",
   "Maat",
   "D. Shantotto",
   "Star Sibyl",
   "Karaha-Baruha",
   "Cid",
   "Gilgamesh",
   "Areuhat",
   "Semih Lafihna",
   "Elivira",
   "Noillurie",
   "Lhu Mhakaracca",
   "Ferreous Coffin",
   "Lilisette",
   "Mumor",
   "Uka Totlihn",
   "Klara",
   "Romaa Mihgo",
   "Kuyin Hathdenna",
   "Rahal",
   "Koru-Moru",
   "Pieuje (UC)",
   "I. Shield (UC)",
   "Apururu (UC)",
   "Jakoh (UC)",
   "Flaviria (UC)",
   "Babban",
   "Abenzio",
   "Rughadjeen",
   "Kukki-Chebukki",
   "Margret",
   "Chacharoon",
   "Lhe Lhangavo",
   "Arciela",
   "Mayakov",
   "Qultada",
   "Adelheid",
   "Amchuchu",
   "Brygid",
   "Mildaurion",
   "Halver",
   "Rongelouts",
   "Leonoyne",
   "Maximilian",
   "Kayeel-Payeel",
   "Robel-Akbel",
   "Kupofried",
   "Selh\'teus",
   "Yoran-Oran (UC)",
   "Sylvie (UC)",
   "Abquhbah",
   "Balamor",
   "August",
   "Rosulatia",
   "Teodor",
   "Ullegore",
   "Makki-Chebukki",
   "King of Hearts",
   "Morimar",
   "Darrcuiln",
   "AAHM",
   "AAEV",
   "AAMR",
   "AATT",
   "AAGK",
   "Iroha",
   "Ygnas",
   "Excenmille [S]",
   "Ayame (UC)",
   "Maat (UC)",
   "Aldo (UC)",
   "Naja (UC)",
   "Lion II",
   "Zeid II",
   "Prishe II",
   "Nashmeira II",
   "Lilisette II",
   "Tenzen II",
   "Mumor II",
   "Ingrid II",
   "Arciela II",
   "Iroha II",
   "Shantotto II",
   "Cornelia",
   "Monberaux",
   "Matsui-P",
}